#!/usr/bin/env bash

# s by s pixels
s=500
m=249 #mid
h=20  #half the side
d=100 #distance separating centers
l=$((m-d)) #left
r=$((m+d)) #right

convert -size 500x500 xc:white -stroke black -fill white \
-draw "line 0,0 5,0" \
-draw "line 494,499 499,499" \
-draw "rectangle $((l-h)),$((l-h)) $((l+h)),$((l+h))" \
-draw "rectangle $((m-h)),$((l-h)) $((m+h)),$((l+h))" \
-draw "rectangle $((r-h)),$((l-h)) $((r+h)),$((l+h))" \
-draw "rectangle $((l-5*h)),$((m-h)) $((l+h)),$((m+h))" \
-draw "rectangle $((m-h)),$((m-h)) $((m+h)),$((m+h))" \
-draw "rectangle $((r-h)),$((m-h)) $((r+h)),$((m+h))" \
-draw "rectangle $((l-h)),$((r-h)) $((l+h)),$((r+h))" \
-draw "rectangle $((l-h)),$((r-h)) $((l+h)),$((r+h))" \
-draw "rectangle $((m-h)),$((r-h)) $((m+h)),$((r+5*h))" \
-draw "rectangle $((r-h)),$((r-h)) $((r+h)),$((r+h))" \
-draw "circle 249,0 329,0" \
-draw "circle 499,249 499,329" \
-draw "circle 400,440 430,440" \
-draw "circle 59,99 59,129" \
awi_multi2.png

#-draw "path 'M 50,0 A 3,1 0 0,0 449,0'" \
#-draw "path 'M 499,50 A 1,3 0 0,0 499,449'" \

# -draw "circle 99,59 129,59" \
# -draw "circle 300,300 310,300" \
#-draw "path 'M 50,0 A 3,1 0 0,0 449,0'" \
# -draw "circle $((r+h)),$((r+h)) $((r+2*h)),$((r+h))" \